name: Deploy to Production

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@139.59.63.142 '
            cd /spunkless &&
            git pull origin master &&
            docker-compose down &&
            docker-compose up -d --build
          '